name: CI for application
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Mysql
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Start mysql
        run: sudo service mysql start

      - name: Create MySQL User
        run: |
          sudo mysql -e "CREATE USER ${{ secrets.MYSQL_USER }}@${{ secrets.MYSQL_HOST }} IDENTIFIED BY ${{ secrets.MYSQL_PASSWORD }};"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO ${{ secrets.MYSQL_USER }}@${{ secrets.MYSQL_HOST }};"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Set up env variables
        run: |
          echo "SQLALCHEMY_DATABASE_URI=mysql+pymysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@${{ secrets.MYSQL_HOST }}:${{ secrets.MYSQL_PORT }}/${{ secrets.MYSQL_DB }}"
          echo "SQLALCHEMY_DATABASE_URI=mysql+pymysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@${{ secrets.MYSQL_HOST }}:${{ secrets.MYSQL_PORT }}/${{ secrets.MYSQL_DB }}" >> $GITHUB_ENV

      - name: Run tests
        run: pytest
