name: CI for application
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB: ${{ secrets.MYSQL_DB }}
      USER: ${{ secrets.MYSQL_USER }}
      PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      HOST: ${{ secrets.MYSQL_HOST }}
      PORT: ${{ secrets.MYSQL_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start mysql
        run: | 
          sudo service mysql start
          sudo service mysql status

      - name: Set up env variables
        run: |
          echo "SQLALCHEMY_DATABASE_URI=mysql+pymysql://$USER:$PASSWORD@$HOST:$PORT/$DB"
          echo "SQLALCHEMY_DATABASE_URI=mysql+pymysql://$USER:$PASSWORD@$HOST:$PORT/$DB" >> $GITHUB_ENV

      - name: Run tests
        run: pytest
