name: CI for application
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start mysql
        run: | 
          sudo service mysql start
          sudo service mysql status

      - name: set env variable
        run: |
          echo "SQLALCHEMY_DATABASE_URI=mysql+pymysql://'${{ secrets.MYSQL_USER }}':'${{ secrets.MYSQL_PASSWORD }}'@'${{ secrets.MYSQL_HOST }}':'${{ secrets.MYSQL_PORT }}'/'${{ secrets.MYSQL_DB }}'"
          echo "SQLALCHEMY_DATABASE_URI=mysql+pymysql://'${{ secrets.MYSQL_USER }}':'${{ secrets.MYSQL_PASSWORD }}'@'${{ secrets.MYSQL_HOST }}':'${{ secrets.MYSQL_PORT }}'/'${{ secrets.MYSQL_DB }}'" >> $GITHUB_ENV 

      - name: Run tests
        run: pytest
