name: Packer:CI for application
on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      FLASK_APP: 'app'
      LOG_FILE: ${{ secrets.LOG_FILE }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      SOURCE_GCI_IMAGE: ${{ secrets.SOURCE_GCI_IMAGE }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_IMAGE_BUILD_NETWORK: ${{ secrets.GCP_IMAGE_BUILD_NETWORK }}
      BUILD_IMAGE_ZONE: ${{ secrets.BUILD_IMAGE_ZONE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: Create webapp.zip
        run: |
          zip -r webapp.zip .

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Install Packer
        run: |
          PACKER_VERSION="1.10.1"
          curl -O https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip -o packer_${PACKER_VERSION}_linux_amd64.zip -d /tmp
          sudo mv /tmp/packer /usr/local/bin
          packer --version

      - name: Initialize Packer Configuration and Format packer file
        run: |
          packer init packer/gci-machine-image.pkr.hcl
          packer fmt -check packer/gci-machine-image.pkr.hcl

      - name: Validate Packer Configuration
        run: |
          packer validate packer/gci-machine-image.pkr.hcl
