name: Packer Build
on:
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      FLASK_APP: 'app'
      LOG_FILE: ${{ secrets.LOG_FILE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start mysql
        run: sudo service mysql start

      - name: setup log file
        run: |
          sudo mkdir -p /var/log/webappLogs
          sudo touch /var/log/webappLogs/webapp.log
          sudo chmod 755 /var/log/webappLogs/webapp.log

      - name: Run tests
        run: pytest -v

      - name: authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Install Packer
        run: |
          PACKER_VERSION="1.10.1"
          curl -O https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer version

      - name: Create webapp.zip
        run: |
          zip -r webapp.zip .

      - name: Initialize Packer Configuration and Format packer file
        run: |
          packer init packer/gci-machine-image.pkr.hcl
          packer fmt packer/gci-machine-image.pkr.hcl

      - name: Validate Packer Configuration
        run: |
          packer validate packer/gci-machine-image.pkr.hcl

      - name: Build Golden Image for GCE
        run: |
          packer build packer/gci-machine-image.pkr.hcl
